apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: daves.example.com
spec:
  group: example.com
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: daves
    singular: dave
    kind: Dave
    shortNames:
    - dv
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cdaves.example.com
spec:
  group: example.com
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: cdaves
    singular: cdave
    kind: ClusterDave
    shortNames:
    - cdv
